BOARD_NAME="STM32MP157C-DK2"
BOARD_FAMILY="stm32mp15"
BOARD_MAINTAINER="rgallaispou"
BOOT_CONFIG="stm32mp157c_dk2_defconfig"
KERNEL_TARGET="current,edge"
KERNEL_TEST_TARGET="current"
PACKAGE_LIST_BOARD="libubootenv-tool apparmor rfkill bluetooth bluez bluez-tools python3-pip watchdog python3-serial python3-intelhex python3-intelhex"
[[ "${RELEASE}" == "jammy" ]] || PACKAGE_LIST_BOARD="${PACKAGE_LIST_BOARD} util-linux-extra"
DEFAULT_CONSOLE="serial"
HAS_VIDEO_OUTPUT="no"
